Repository antisedativ/CharmLog, pull requests merged in 2024-02, with the labels that each got.

#18 CLT-23 Разработка цветных методов
  src/index.js
  src/oneColor/colorMethod.js
  tests/methods/colorMethod.test.js
Labels: enhancement

#19 CLT-20 add logger
  src/index.js
  src/logger/Logger.js
  src/utils/constants.js
Labels: enhancement

#20 CLT-40 logger tests
  src/logger/Logger.js
  tests/methods/Logger.test.js
Labels: technical

#32 CLT-43 add spread syntax
  src/formatters/LogFormatter.js
  src/oneColor/colorMethod.js
  src/rainbow/rainbowMethod.js
Labels: bug
